name: Health Checker (Keep Render Alive)

on:
  schedule:
    - cron: "*/7 * * * *" # every 7 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Engine directly
        run: |
          echo "[$(date)] Pinging Engine..."
          ENGINE_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://beriko-engine.onrender.com/ || true)
          echo "Engine status: $ENGINE_RESPONSE"

      - name: Ping API (which calls Engine)
        run: |
          echo "[$(date)] Pinging API health route..."
          API_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://beriko-api.onrender.com/ || true)
          echo "API status: $API_RESPONSE"

          if [ "$API_RESPONSE" -eq 200 ]; then
            echo "✅ API and Engine are both awake!"
          else
            echo "⚠️ API or Engine might still be waking (Status: $API_RESPONSE)"
          fi
